services:
  chatsemban:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./tokens.json:/app/tokens.json
      - ./active.json:/app/active.json
      - ./media:/app/dist/media
